### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by formath** [dmlc/difacto#16]

**Comment by yitang** [comment]
+1

**Comment by CNevd** [comment]
the wormhole version of difacto is still available based on ps-lite V1: [Difacto_DMLC](https://github.com/CNevd/Difacto_DMLC) and look forward to mu's new difacto being done:)

**Comment by BaiGang** [comment]
Basically we need a distributed implementation of store and a distributed tracker.

**Comment by geffy** [comment]
+1, interested in progress/news.

**Comment by kopopt** [comment]
@formath @yitang @CNevd @BaiGang  As a fun project for learning tensorflow, I developed an distributed factorization machine based on tensorflow. It has comparable performance with difacto and support distributed learning. Welcome to take a look and give some suggestions. Thanks.

https://github.com/kopopt/fast_tffm

**Comment by yitang** [comment]
@kopopt it looks good, I will find a chance to try it.
